# Generated by Django 3.0.1 on 2019-12-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0004_customer_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salry',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
